all:
	dia DiagramaClasesAnalisis.dia -e DiagramaClasesAnalisis.eps
	dia DiagramaClasesDisennoTelnet.dia -e DiagramaClasesDisennoTelnet.eps
	dia DiagramaFlujoHTTP.dia -e DiagramaFlujoHTTP.eps
	dia DiagramaFlujoSIP.dia -e DiagramaFlujoSIP.eps
	dia DiagramaFlujoTelnet.dia -e DiagramaFlujoTelnet.eps
	dia FlujoServicio.dia -e FlujoServicio.eps
	dia NivelesOSI.dia -e NivelesOSI.eps
